2 ：
import?java.util.*;
public?class?Test{
public?static?void?main(String[]?args){
System.out.println("班级:"+"软件工程1501"+'\n'+"学号:"+"201516920301"+'\n'+"姓名:"+"杨万理");
}
}

3：
import?java.util.*;
public?class?Test{
static?int?Addition(int?num){
int?sum=0,b;
while(num!=0){
b=num%10;
num=num/10;
sum+=b;
}
return?sum;
}
public?static?void?main(String[]?args){
Scanner?input=new?Scanner(System.in);
int?num=0;
System.out.println("请输入一个整数：");
num=input.nextInt();
System.out.println("您输入的数字为："+num+'\n'+"各个位数之和为："+Addition(num));
}
}

4：
import?java.util.*;
public?class?Test{
static?boolean?Fun(int?num){
int?a=num/100,b=num%10,c=num/10%10;
if?(a*a*a+b*b*b+c*c*c==num)
return?true;
else
return?false;
}
public?static?void?main(String?[]?args){
System.out.println("请输入一个三位整数：");
Scanner?input=new?Scanner(System.in);
int?num=0;
num=input.nextInt();
if(Fun(num))
System.out.println(num+"是水仙花数");
else
System.out.println(num+"不是水仙花数");

}
}